# Generated by Django 4.2.2 on 2024-05-14 09:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import events_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='BonusTeamLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Bonus Team Log',
                'verbose_name_plural': 'Bonus Team Logs',
            },
        ),
        migrations.CreateModel(
            name='BonusUserLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Bonus User Log',
                'verbose_name_plural': 'Bonus User Logs',
            },
        ),
        migrations.CreateModel(
            name='ContestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events_app.event')),
                ('score', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendances',
            },
            bases=('events_app.event',),
        ),
        migrations.CreateModel(
            name='BonusTeam',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events_app.event')),
            ],
            options={
                'verbose_name': 'Team Bonus',
                'verbose_name_plural': 'Team Bonuses',
            },
            bases=('events_app.event',),
        ),
        migrations.CreateModel(
            name='BonusUser',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events_app.event')),
            ],
            options={
                'verbose_name': 'User Bonus',
                'verbose_name_plural': 'User Bonuses',
            },
            bases=('events_app.event',),
        ),
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events_app.event')),
            ],
            options={
                'verbose_name': 'Contest',
                'verbose_name_plural': 'Contests',
            },
            bases=('events_app.event',),
        ),
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events_app.event')),
                ('promo_code', models.CharField(db_index=True, default=events_app.models.generate_promo, max_length=20, unique=True)),
                ('code_type', models.IntegerField(choices=[(1, 'User'), (2, 'Team')], default=0, verbose_name='Promo type')),
                ('condition', models.IntegerField(choices=[(1, 'Active'), (2, 'Used')], default=0)),
                ('used_by', models.CharField(blank=True, default=None, max_length=100)),
                ('score', models.IntegerField(default=0)),
                ('message', models.TextField(default='Промокод был активирован', max_length=100)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('events_app.event',),
        ),
    ]
