# Generated by Django 4.2.2 on 2024-05-14 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestlog',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_app.team'),
        ),
        migrations.AddField(
            model_name='bonususerlog',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bonusteamlog',
            name='team',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users_app.team'),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contestlog',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events_app.contest'),
        ),
        migrations.AddField(
            model_name='bonususerlog',
            name='bonus',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='events_app.bonususer'),
        ),
        migrations.AddField(
            model_name='bonusteamlog',
            name='bonus',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='events_app.bonusteam'),
        ),
        migrations.AddField(
            model_name='attendancelog',
            name='attendance',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='events_app.attendance'),
        ),
    ]
