# Generated by Django 4.2.2 on 2024-05-14 09:26

import bot_app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('response', models.TextField(blank=True, default='Ответ получен, спасибо!', max_length=100, null=True)),
                ('activated', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('details', models.TextField()),
                ('traceback_page', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='RegistryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=100)),
                ('count', models.IntegerField(default=0)),
                ('max', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('status', models.CharField(choices=[('RC', 'Получено'), ('AP', 'Принято в обработку'), ('D', 'Выполнено'), ('CL', 'Закрыто'), ('CN', 'Отменено')], default='RC', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='ResponseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default=bot_app.models.generateKey, max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VoteOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=100)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('responselog_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bot_app.responselog')),
                ('text', models.TextField(max_length=400)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('bot_app.responselog',),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('broadcast_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bot_app.broadcast')),
                ('text', models.TextField(blank=True, max_length=400, null=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('bot_app.broadcast',),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('broadcast_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bot_app.broadcast')),
                ('text', models.TextField(max_length=400)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('bot_app.broadcast',),
        ),
        migrations.CreateModel(
            name='Registry',
            fields=[
                ('broadcast_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bot_app.broadcast')),
                ('text', models.TextField(max_length=500)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('bot_app.broadcast',),
        ),
        migrations.CreateModel(
            name='RegistryLog',
            fields=[
                ('responselog_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bot_app.responselog')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('bot_app.responselog',),
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('broadcast_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bot_app.broadcast')),
                ('text', models.TextField(max_length=400)),
                ('close_time', models.TimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('bot_app.broadcast',),
        ),
        migrations.CreateModel(
            name='VoteLog',
            fields=[
                ('responselog_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bot_app.responselog')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('bot_app.responselog',),
        ),
    ]
