# Generated by Django 4.2.2 on 2024-05-14 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('events_app', '0002_initial'),
        ('users_app', '0001_initial'),
        ('bot_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voteoption',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users_app.team'),
        ),
        migrations.AddField(
            model_name='responselog',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='responselog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='report',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='broadcast',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='broadcast',
            name='users',
            field=models.ManyToManyField(default=users_app.models.User.all_users, related_name='users_list', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='voteoption',
            name='voting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_options', to='bot_app.vote'),
        ),
        migrations.AddField(
            model_name='votelog',
            name='broadcast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bot_app.vote'),
        ),
        migrations.AddField(
            model_name='votelog',
            name='voted_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bot_app.voteoption'),
        ),
        migrations.AddField(
            model_name='vote',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='events_app.event'),
        ),
        migrations.AddField(
            model_name='registrylog',
            name='broadcast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bot_app.registry'),
        ),
        migrations.AddField(
            model_name='registrylog',
            name='voted_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bot_app.registryevent'),
        ),
        migrations.AddField(
            model_name='registryevent',
            name='registry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='bot_app.registry'),
        ),
        migrations.AddField(
            model_name='registry',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='events_app.event'),
        ),
        migrations.AddField(
            model_name='answer',
            name='broadcast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bot_app.question'),
        ),
    ]
